# Generated by Django 3.2.8 on 2022-05-12 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workout', '0006_rename_kcal_consumption_dayhistoryworkout_workout_kcal_consumption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayhistoryextraworkout',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_history_extra_workout', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DayHistoryWorkoutWrongPoses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrong_pose', models.CharField(max_length=200)),
                ('dayHistoryWorkout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_history_workout_wrong_poses', to='workout.dayhistoryworkout')),
            ],
        ),
        migrations.CreateModel(
            name='DayHistoryExtraWorkoutWrongPoses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrong_pose', models.CharField(max_length=200)),
                ('dayHistoryExtraWorkout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_history_extra_workout_wrong_poses', to='workout.dayhistoryextraworkout')),
            ],
        ),
    ]
